coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 0%
        informational: true
    patch:
      default:
        target: 90%
        threshold: 0%
        informational: true
