[build-system]
requires = ["setuptools>=64", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "bids2table"
dynamic = ["version"]
authors = [
    { name = "Connor Lane", email = "connor.lane858@gmail.com" },
]
description = "Index BIDS datasets"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT License"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
]

dependencies = [
    "bidsschematools==1.0.5",
    "numpy<2",
    "pyarrow==11.0.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-cov>=6.0.0",
    "pre-commit>=4.1.0",
    "ruff>=0.9.10",
    "ipython>=9.2.0",
]

[project.urls]
"Homepage" = "https://github.com/childmindresearch/bids2table"
"Issues" = "https://github.com/childmindresearch/bids2table/issues"

[tool.setuptools.packages.find]
include = ["bids2table*"]

[tool.setuptools_scm]
version_file = "bids2table/_version.py"

[tool.ruff]
line-length = 88
target-version = "py311"
lint.extend-select = ["I"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
