[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "bids2table"
description = "Efficiently index large-scale BIDS datasets and derivatives"
authors = [
    {name = "Connor Lane", email = "connor.lane858@gmail.com"},
]
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT License"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "elbow",
    "nibabel",
    "pandas",
]
dynamic = ["version"]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]
dev = [
    "pdoc==14.0.0",
    "black==23.3.0",
    "flake8==5.0.4",
    "isort==5.11.5",
    "mypy==1.2.0",
    "pre-commit",
    "pylint>=2.5.0",
    "setuptools-scm",
]

[project.urls]
"Homepage" = "https://github.com/childmindresearch/bids2table"

[project.scripts]
bids2table = "bids2table.__main__:main"
b2t = "bids2table.__main__:main"

[tool.setuptools.packages.find]
include = ["bids2table*"]

[tool.setuptools_scm]
write_to = "bids2table/_version.py"

[tool.black]
line-length = 88
target_version = ['py37']

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"

[tool.mypy]
no_strict_optional = true
ignore_missing_imports = true
