name: Benchmark

on:
  pull_request:
    branches: ["main"]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
          ref: ${{ github.head_ref }}
      - uses: astral-sh/setup-uv@v8.1.0
      - run: uv sync --frozen --all-extras
      - name: Run benchmarks
        id: run-benchmarks
        run: |
          uv run python scripts/benchmark.py --branch $BRANCH_NAME
      - uses: actions/upload-artifact@v7
        with:
          name: benchmark-${{ matrix.target.name }}
          path: ${{ steps.run-benchmarks.outputs.report_file }}
