name: Benchmark

permissions:
  contents: read

on:
  pull_request:
    branches: ["main"]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
          ref: ${{ github.head_ref }}
      - uses: astral-sh/setup-uv@v8.1.0
      - run: uv sync --frozen --all-extras
      - name: Run benchmarks
        id: run-benchmarks
        run: |
          uv run python scripts/benchmark.py -b $BRANCH_NAME -o . -f benchmarks.md -t 0.05
      - name: Record pr number
        run: |
          echo "${{ github.event.number }}" > pr-number.txt
      - uses: actions/upload-artifact@v7
        with:
          name: benchmark
          retention-days: 7
          path: |
            benchmarks.md
            pr-number.txt
